### ISSUE TITLE
PGsharp Beta download doesn't work anymore

### ISSUE THREAD

**Issue by Radriant** [RealIndica/PGS-Standalone-Installer#4]
Since the beta apk is now only available from a Mega.nz link the app now fails to download it

**Comment by RealIndica** [comment]
I will need to integrate a Mega API because of the way Mega download files, expect an update soon.

**Comment by RealIndica** [comment]
Beta download is now fixed and supports Mega.nz

866ddd098994f1ba2648a5ad52f474c0c22b5384
