### ISSUE TITLE
Standalone and Vanilla version can't be installed on the same device at the same time

### ISSUE THREAD

**Issue by Radriant** [RealIndica/PGS-Standalone-Installer#5]
Standalone PGSharp version 1.72.1 and PoGO ver 0.241.0-G can no longer be installed on the same device at the same time, I would apresiate if you could check it out and fix it

**Comment by RealIndica** [comment]
Hey, I haven't messed with pogo in quite a while now. I will definitely have a look when I get hooked on it again haha

**Comment by Radriant** [comment]
That's understable, the game seems to be steadily getting worse and worse

**Comment by RealIndica** [comment]
This is been fixed :) 

f037792f161e6ca3f9cc90600999d65b88538617
